### ISSUE TITLE
Missing WinApp Project

### ISSUE THREAD

**Issue by sagar-patel-sls** [saberzahed/LoRaWAN.Packet.Decoder#1]
Missing WinApp Project in solution

**Comment by saberzahed** [comment]
> Missing WinApp Project in solution

This is standard .net library. you can add refrence and use in your .net core or .net framework a

**Comment by sagar-patel-sls** [comment]
> > Missing WinApp Project in solution
> 
> This is standard .net library. you can add refrence and use in your .net core or .net framework a

Thank you
